"""Integration tests for the trust boundary system (Phase A + Phase B judge pattern)."""

import json

from carpenter.core.arcs import manager as arc_manager
from carpenter.core.workflows import review_manager
from carpenter.core.trust.encryption import (
    generate_arc_key, encrypt_output, decrypt_for_reviewer,
)
from carpenter.tool_backends import arc as arc_backend
from carpenter.db import get_db


def test_full_trust_lifecycle():
    """Complete trust flow with judge: untrusted → encrypt → review → judge → promote → decrypt."""
    # 1. Create an untrusted arc with reviewers + judge via batch
    parent = arc_manager.create_arc("project")
    result = arc_backend.handle_create_batch({
        "arcs": [
            {
                "name": "web-scraper",
                "parent_id": parent,
                "integrity_level": "untrusted",
            },
            {
                "name": "security-review",
                "parent_id": parent,
                "agent_type": "REVIEWER",
                "reviewer_profile": "security-reviewer",
            },
            {
                "name": "judge",
                "parent_id": parent,
                "agent_type": "JUDGE",
                "reviewer_profile": "judge",
            },
        ]
    })

    target, reviewer, judge = result["arc_ids"]

    # 2. Get the Fernet key (already generated by batch creation)
    db = get_db()
    try:
        row = db.execute(
            "SELECT fernet_key_encrypted FROM review_keys "
            "WHERE target_arc_id = ? AND reviewer_arc_id = ? LIMIT 1",
            (target, reviewer),
        ).fetchone()
        key = bytes(row["fernet_key_encrypted"])
    finally:
        db.close()

    # 3. Encrypt some output
    plaintext = "sensitive scraped data: password=hunter2"
    ciphertext = encrypt_output(key, plaintext)
    assert ciphertext != plaintext.encode()

    # 4. Store encrypted output as arc state
    db = get_db()
    try:
        db.execute(
            "INSERT INTO arc_state (arc_id, key, value_json) VALUES (?, ?, ?)",
            (target, "_output", json.dumps(ciphertext.decode("ascii"))),
        )
        db.commit()
    finally:
        db.close()

    # 5. Reviewer decrypts and approves (advisory only)
    decrypted = decrypt_for_reviewer(reviewer, target, ciphertext)
    assert decrypted == plaintext

    result = review_manager.submit_verdict(reviewer, target, "approve", "safe to use")
    assert result["promoted"] is False  # Reviewer approval doesn't promote

    # 6. Judge approves → trust promotion
    result = review_manager.submit_verdict(judge, target, "approve", "final approval")
    assert result["promoted"] is True

    # 7. Verify target is promoted
    arc = arc_manager.get_arc(target)
    assert arc["integrity_level"] == "trusted"


def test_rejection_flow():
    """Judge rejection → target arc fails, stays untrusted."""
    parent = arc_manager.create_arc("project")
    result = arc_backend.handle_create_batch({
        "arcs": [
            {
                "name": "risky-code",
                "parent_id": parent,
                "integrity_level": "untrusted",
            },
            {
                "name": "security-review",
                "parent_id": parent,
                "agent_type": "REVIEWER",
                "reviewer_profile": "security-reviewer",
            },
            {
                "name": "judge",
                "parent_id": parent,
                "agent_type": "JUDGE",
                "reviewer_profile": "judge",
            },
        ]
    })

    target, reviewer, judge = result["arc_ids"]
    arc_manager.update_status(target, "active")

    # Reviewer rejects (advisory only, no effect)
    result1 = review_manager.submit_verdict(reviewer, target, "reject", "injection risk")
    assert result1["promoted"] is False
    arc = arc_manager.get_arc(target)
    assert arc["status"] == "active"  # Still active

    # Judge rejects → arc fails
    result2 = review_manager.submit_verdict(judge, target, "reject", "security risk")
    assert result2["promoted"] is False

    # Verify target stays untrusted and is failed
    arc = arc_manager.get_arc(target)
    assert arc["integrity_level"] == "untrusted"
    assert arc["status"] == "failed"


def test_judge_pattern_replaces_quorum():
    """Judge pattern: only judge verdict matters, not reviewer count."""
    parent = arc_manager.create_arc("project")
    result = arc_backend.handle_create_batch({
        "arcs": [
            {
                "name": "external-api-call",
                "parent_id": parent,
                "integrity_level": "untrusted",
            },
            {
                "name": "security-review",
                "parent_id": parent,
                "agent_type": "REVIEWER",
                "reviewer_profile": "security-reviewer",
            },
            {
                "name": "ux-review",
                "parent_id": parent,
                "agent_type": "REVIEWER",
                "reviewer_profile": "security-reviewer",
            },
            {
                "name": "judge",
                "parent_id": parent,
                "agent_type": "JUDGE",
                "reviewer_profile": "judge",
            },
        ]
    })

    target, r1, r2, judge = result["arc_ids"]

    # Both reviewers approve (advisory only)
    review_manager.submit_verdict(r1, target, "approve", "security ok")
    review_manager.submit_verdict(r2, target, "approve", "ux ok")

    # Target still not promoted (need judge)
    arc = arc_manager.get_arc(target)
    assert arc["integrity_level"] == "untrusted"

    # Judge approves → promoted
    result = review_manager.submit_verdict(judge, target, "approve", "final approval")
    assert result["promoted"] is True

    arc = arc_manager.get_arc(target)
    assert arc["integrity_level"] == "trusted"
